### ISSUE TITLE
User profiles should be extensible (e.g. to support ORCID Ids)

### ISSUE THREAD

**Issue by eamonnmag** [inveniosoftware/invenio-userprofiles#27]
For me it makes sense. Most users of invenio software are likely to be some how involved in the sciences. And even if they don't, it doesn't hurt to have that.

**Comment by jirikuncar** [comment]
@eamonnmag ORCID is handled by `invenio-oauthclient`.

**Comment by kaplun** [comment]
@eamonnmag did you mean whether to have the ORCID into user profile, regardless of having used ORCID authentication? (a bit like having an email, or a nickname?)

**Comment by eamonnmag** [comment]
@kaplun exactly.

**Comment by kaplun** [comment]
Looking at `invenio-userprofiles` model, indeed, I can't see how user profile can be extended to fit an Invenio instance specific field requirements (such as ORCID ID).

**Comment by egabancho** [comment]
Indeed I think we should be able to extend the user profile somehow in our overlays, like @kaplun pointed out.
But I don't think adding the ORCID ID directly to the user profile is the way to do it, if we do it like @eamonnmag, why not adding also the GitHub account information, or  the CERN ID, or the Inspire ID ...

**Comment by eamonnmag** [comment]
Well indeed. Any of these would be valid. Django profiles has nice ways to
extend the user profile model to encompass any information the implementing
system wants to carry about their users. ORCID for me was one I wanted
since I can pull their ORCID profile information in to the user dashboard
automatically with all their biography,  work information,  and
publications.

**Comment by jirikuncar** [comment]
One should also consider using authority records for storing such information.

**Comment by lnielsen** [comment]
Regarding ORCID in the user profile - it's recommended by ORCID to never have a user enter their ORCID but always go through oauth flow (see "ORCID branding in technical integrations" in bottom of page https://orcid.org/trademark-and-id-display-guidelines). I.e. invenio-oauthclient does the job - that said I think display wise it can make fully sense to display the ORCID on a profile page.

Regarding extendable user profiles - yep, I fully agree that would be very nice and yes Django has a nice way of doing this. Currently we implemented basic functionality (username/full name) as this is needed to port existing sites.  

Downside is I don't think anyone has actually time to work on this. So would go in the "someday" category for me.

**Comment by eamonnmag** [comment]
Ok, no problem :)

**Comment by lnielsen** [comment]
@eamonnmag It shouldn't prevent you from making a PR ;-) but if you don't have time I would close it and tag it with milestone someday.

**Comment by eamonnmag** [comment]
Indeed :) I may do it anyway since I want to create a dashboard based partly on the ORCID information. I wasn't so careful with controlling how ORCIDs were entered before. I didn't see many users going around copying someone else's profile to make themselves look better or worse. But, as long as we have the facility to maintain these IDs, it can be up to developers to control how these identifiers and account details are dealt with for their own applications.

**Comment by jirikuncar** [comment]
@eamonnmag please see `RemoteAccount` model - https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/models.py#L35

Do you propose to move it in Invenio-Accounts if you are not using Invenio-OAuthClient?

**Comment by eamonnmag** [comment]
Yes, that would be perfect.
