### ISSUE TITLE
Installation: Incompatible clean-css dependency.

### ISSUE THREAD

**Issue by guptavaibhav18197** [inveniosoftware/invenio-userprofiles#71]
latest version of clean-css incompatible with current code and missing clean-css-cli. Hence throwing installation errors while running ```flask assets build```.

**Comment by lnielsen** [comment]
We've supplied an upstream patch to ``webassets`` module to support both v3 and v4 of clean-css. See miracle2k/webassets#486

**Comment by guptavaibhav18197** [comment]
Addressed by pull #70 .
So can be closed now.
