### ISSUE TITLE
Installation error: alot of files not found error in examples/static/{js,scss,css} on running app-setup.sh 

### ISSUE THREAD

**Issue by guptavaibhav18197** [inveniosoftware/invenio-userprofiles#72]
A lot of files were not found error prompted during execution of ```flask assets build```
like : /static/js/csv_previewer/init.js no such file error, leading to termination of bundles building process.

**Comment by hjhsalo** [comment]
Tried just a second ago on Ubuntu 16.04 and seems to be working now:
```
$ pip install -e .[all]
$ docker run --rm -p 6379:6379 redis
$ ./run-tests.sh 
$ cd examples
$ ./app-setup.sh
$ ./app-fixtures.sh
$ FLASK_APP=app.py flask run --debugger -p 5000
$ curl 127.0.0.1:5000
$ ./app-teardown.sh
```
I'm closing the issue and reopening if needed.
