### ISSUE TITLE
docs: how to extend invenio-accounts REST API

### ISSUE THREAD

**Issue by mvidalgarcia** [inveniosoftware/invenio-userprofiles#97]
If user wants `invenio-userprofiles` using the invenio-accounts REST API, they have to take into account that the `RegisterView` should be extended, as mentioned [here](https://github.com/inveniosoftware/invenio-accounts/issues/304).

In particular [`username` and `fullname`](https://github.com/inveniosoftware/invenio-userprofiles/blob/aa37ba68d2b8e3fd4b97e688db4961eb7b2d0640/invenio_userprofiles/forms.py#L46-L58).

**Comment by lnielsen** [comment]
Implemented via Invenio-Users-Resources
